on:
  push:
    branches: [main, master]
  workflow_dispatch: {}

name: r-wasm/actions - repo

jobs:
  reuse-workflow-repo:
    uses: ./.github/workflows/deploy-cran-repo.yml
    with:
      packages: cubature
    permissions:
      repository-projects: read
      pages: write
      id-token: write
